version: "3"
services:
  db:
    container_name: db
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qr
      - POSTGRES_USER=qrmaster
      - POSTGRES_PASSWORD=baguvix123FFF
    ports:
      - "5433:5433"
  web:
    container_name: web
    build:
      context: .
    command: "gunicorn --bind 0.0.0.0:8001 qrmenu.wsgi:application"
    environment:
      CONTAINER_TYPE: DJANGO
    volumes:
      - ./qr-back:/app/
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres_data: