# Generated by Django 5.0.1 on 2024-02-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveIntegerField(blank=True, null=True)),
                ('user_uuid', models.UUIDField(blank=True, null=True)),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waiter.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiter.waitertable')),
            ],
        ),
    ]
