# Generated by Django 5.0.1 on 2024-02-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_waitertable_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitertable',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
