# Generated by Django 5.0.1 on 2024-02-23 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_store_user'),
        ('waiter', '0003_alter_waitertable_waiter_delete_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='menu.store'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='menu.food'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='waiter.waitertable'),
        ),
    ]
