# Generated by Django 5.0.1 on 2024-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_user_store_alter_fooditem_food_alter_fooditem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitertable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
