# Generated by Django 5.0.1 on 2024-07-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
